Repository E1sh3r2/E1sh3r2.github.io, pull requests merged in 2022-05, with the labels that each got.

#9 Feature/new design
  README.md
  assets/css/main.css
  assets/fonts/RedHatDisplay-Bold.otf
  assets/fonts/RedHatDisplay-Regular.otf
  assets/fonts/SIL Open Font License.txt
  assets/js/main.js
  assets/js/md-parser.js
  assets/svg/thumbs-down.svg
  assets/svg/thumbs-up.svg
  index.css
  index.html
  index.js
  markdownparser.py
  questions.js
  questions.markdown
Labels: enhancement

#16 add favicons + add favicon tags to index.html
  assets/favicon/android-icon-144x144.png
  assets/favicon/android-icon-192x192.png
  assets/favicon/android-icon-36x36.png
  assets/favicon/android-icon-48x48.png
  assets/favicon/android-icon-72x72.png
  assets/favicon/android-icon-96x96.png
  assets/favicon/apple-icon-114x114.png
  assets/favicon/apple-icon-120x120.png
  assets/favicon/apple-icon-144x144.png
  assets/favicon/apple-icon-152x152.png
  assets/favicon/apple-icon-180x180.png
  assets/favicon/apple-icon-57x57.png
  assets/favicon/apple-icon-60x60.png
  assets/favicon/apple-icon-72x72.png
  assets/favicon/apple-icon-76x76.png
  assets/favicon/apple-icon-precomposed.png
  assets/favicon/apple-icon.png
  assets/favicon/browserconfig.xml
  assets/favicon/favicon-16x16.png
  assets/favicon/favicon-32x32.png
  assets/favicon/favicon-96x96.png
  assets/favicon/favicon.ico
  assets/favicon/manifest.json
  assets/favicon/ms-icon-144x144.png
  assets/favicon/ms-icon-150x150.png
  assets/favicon/ms-icon-310x310.png
  assets/favicon/ms-icon-70x70.png
  index.html
Labels: enhancement

#15 remove closure and add comments
  assets/js/main.js
Labels: documentation

#20 fix bug chome mobile 100vh
  assets/css/main.css
Labels: bug

#19 add new questions; refactor some old questions
  assets/css/main.css
  questions.markdown
Labels: enhancement
